[tool.poetry]
name = "python-rabbitmq-exercise"
version = "0.1.0"
description = ""
authors = ["Goshan57 <485262323@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pika = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
